export const REGISTRATION_OR_SIGN_IN_PENDING = "REGISTRATION_OR_SIGN_IN_PENDING";
export const REGISTRATION_OR_SIGN_IN_SUCCESS = "REGISTRATION_OR_SIGN_IN_SUCCESS";
export const REGISTRATION_OR_SIGN_IN_FAILURE = "REGISTRATION_OR_SIGN_IN_FAILURE";
export const REGISTRATION_OR_SIGN_IN_ERROR_RESET = "REGISTRATION_OR_SIGN_IN_ERROR_RESET";
export const LOAD_USER = "LOAD_USER";
export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const ROUTE_CHANGE = "ROUTE_CHANGE";
