export const LOAD_USER = "LOAD_USER";
export const ROUTE_CHANGE = "ROUTE_CHANGE";

// export const SIGN_IN_PENDING = "SIGN_IN_PENDING";
// export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
// export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
// export const REGISTRATION_PENDING = "REGISTRATION_PENDING";
// export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
// export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";
// export const REGISTRATION_RESET = "REGISTRATION_RESET"
